---
title: Projects
---
# Overview(Please click link if you wonder further detial)

## [HR Attrition Project](./projects/HR Attrition Project/)

Employee retention is crucial for organizational stability, as high turnover disrupts operations and increases costs. This study leverages the IBM HR Analytics Employee Attrition & Performance dataset, containing 35 attributes like satisfaction, compensation, and performance, to analyze turnover trends. By applying machine learning models—Random Forest, Logistic Regression, and K-Nearest Neighbors—the project aims to predict attrition risk, identify key factors driving employee turnover, and provide actionable insights. Understanding these patterns helps HR departments proactively retain talent, reduce recruitment expenses, and maintain a competitive edge in today’s talent-driven market, ultimately fostering a stable and productive workforce.

## [Spam Detection Project](./projects/Spam Detection Project/)

This project builds a machine learning model to classify SMS messages as spam or ham (non-spam) using Natural Language Processing (NLP) techniques. To address class imbalance, it applies SMOTE (Synthetic Minority Oversampling Technique). Various classifiers are tested, and model performance is evaluated using accuracy, precision, recall, F1-score, and AUC. The best results are achieved using a Naïve Bayes classifier with TF-IDF vectorization and N-gram features (unigram, bigram, trigram). A live demo is also developed to showcase real-time spam detection. This project highlights the importance of automated spam detection in the face of increasing spam message volume.

## [Statistic Data Analysis Project](./projects/Statistic Data Analysis/)

This project explores the complexity of human kissing behavior in romantic relationships, which goes beyond biological instincts to foster emotional connection. It investigates factors influencing "Kiss Frequency," including partner attractiveness, kiss satisfaction, and broader societal influences like national GDP and the GINI index. The study aims to understand how both personal and environmental factors affect kissing habits. Unlike other animals, humans kiss more frequently in love, and this behavior may vary based on relationship type and surroundings. The analysis offers new insights into the cultural and economic aspects of kissing, with findings detailed in later sections of the report.

## [Sun County Airline Project](./projects/Sun County Airline Project/)

This project supports Sun Country Airlines' growth by using data-driven strategies to enhance customer engagement and loyalty. Using data from January 2013 to December 2014 (37 columns, 26,575 rows), we applied K-means Cluster Analysis and visualized results using Excel, Python, and Power BI. This enabled us to group customers by similar behaviors and preferences, supporting Precision Marketing efforts. Visualizations helped identify key segments and generate actionable insights to strengthen customer relationships and build a sustainable competitive advantage.

## [Beyond Meat Marketing Project](./projects/Beyond Meat MKT Proj/)

This project aims to address the potential issues arising in plant-based market, especially for Beyond Meat. This project provided some suggestions for Beyond Meat in Product and Sales Channel aspects.