project:
  type: website

website:
  title: "Xinru Zhao Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Self-Intro
      - href: projects/
        text: Projects

          


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

